export { Header } from "./Header"
export { Layout } from "./Layout"
export { LayoutGeneral } from "./LayoutGeneral"
export {  MenuView, DescargarApp, HeroSesion} from "./Componentes"
export { CategoriasDestacados } from "./Componentes"
export { PorqueElegirnos } from "./Componentes"
export { TodosLosProductos } from "./Componentes"
export { Calidad } from "./Componentes"
export { Testimonios } from "./Componentes"
export { FooterCredits } from "./Componentes"
